
global:
  edition: ce

  hosts:
    domain: DOMAIN_PLACEHOLDER
    https: false

  ingress:
    enabled: true
    configureCertmanager: false
    provider: nginx
    tls:
      enabled: false

  gatewayApi:
    enabled: false

  psql:
    host: postgres.gitlab.svc.cluster.local
    port: 5432
    username: gitlab
    database: gitlabhq_production
    password:
      secret: gitlab-postgres-password
      key: password

  redis:
    host: redis.gitlab.svc.cluster.local
    port: 6379
    auth:
      enabled: false

  appConfig:
    object_store:
      enabled: true
      connection:
        secret: gitlab-object-storage
        key: connection
    lfs:
      bucket: git-lfs
    artifacts:
      bucket: gitlab-artifacts
    uploads:
      bucket: gitlab-uploads
    packages:
      bucket: gitlab-packages
    backups:
      bucket: gitlab-backups

installCertmanager: false

certmanager-issuer:
  email: admin@example.com

nginx-ingress:
  enabled: true
  controller:
    service:
      type: LoadBalancer
    replicaCount: 1

registry:
  enabled: false

gitlab-runner:
  install: false

prometheus:
  install: false

gitlab-zoekt:
  install: false

openbao:
  install: false

gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: 300m
        memory: 900Mi
      limits:
        cpu: "1"
        memory: 2200Mi
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: 150m
        memory: 600Mi
      limits:
        cpu: "1"
        memory: 2000Mi
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
  gitaly:
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
  toolbox:
    backups:
      objectStorage:
        backend: azure
