
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "jhogoncaS" do |s|
    s.vm.hostname = "jhogoncaS"
    s.vm.network "private_network", ip: "192.168.56.110"
    s.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 1
    end
    s.vm.provision "shell", path: "scripts/setup.sh"
  end
end
