# -*- mode: ruby -*-

# Vagrantfile for configuring virtual machine infrastructure using Vagrant
#
# This file uses Vagrant configuration API version 2, which is the current standard
# for defining Vagrant environments. API version 2 provides support for:
# - Multiple provider backends (VirtualBox, VMware, AWS, etc.)
# - Multiple virtual machines in a single configuration
# - Improved syntax and configuration options compared to API version 1
# - Better provisioning and networking capabilities
#
# The version 2 API is specified by passing "2" to Vagrant.configure()


# Configure Vagrant with version 2 API
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  # SERVER (S)
  config.vm.define "jhogoncaS" do |s|
    s.vm.hostname = "jhogoncaS"
    s.vm.network "private_network", ip: "192.168.56.110"
    s.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    s.vm.provision "shell", path: "scripts/setup_server.sh"
  end

  # WORKER (SW)
  config.vm.define "jhogoncaSW" do |sw|
    sw.vm.hostname = "jhogoncaSW"
    sw.vm.network "private_network", ip: "192.168.56.111"
    sw.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
    sw.vm.provision "shell", path: "scripts/setup_worker.sh"
  end
end