
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.boot_timeout = 600

  k3s_token = "iot-k3s-cluster-token"

  config.vm.define "jhogoncaS" do |s|
    s.vm.hostname = "jhogoncaS"
    s.vm.network "private_network", ip: "192.168.56.110"
    s.vm.provider "virtualbox" do |vb|
      vb.memory = "1536"
      vb.cpus = 1
    end
    s.vm.provision "shell", path: "scripts/setup_server.sh", env: { "K3S_TOKEN" => k3s_token }
  end

  config.vm.define "jhogoncaSW" do |sw|
    sw.vm.hostname = "jhogoncaSW"
    sw.vm.network "private_network", ip: "192.168.56.111"
    sw.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    sw.vm.provision "shell", path: "scripts/setup_worker.sh", env: { "K3S_TOKEN" => k3s_token }
  end
end
