Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "jhogoncaBonus"
  config.vm.network "private_network", ip: "192.168.56.130"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "10240"
    vb.cpus = 4
  end
  config.vm.provision "shell", path: "scripts/setup.sh", privileged: false
end
